version: '3.3'
services:
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      CLIENT_ID: INSERT ID
      CLIENT_SECRET: INSERT SECRET
      REDIRECT_URI: http://localhost:8080/spotify
    ports:
      - '8080:8080'