version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
      CLIENT_ID: INSERT ID
      CLIENT_SECRET: INSERT SECRET
      REDIRECT_URI: http://localhost:8080/spotify
    ports:
      - '8080:8080'